//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontNameSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimAircraftRemote
    {
        public int AcftID { get; set; }
        public string AcftNum { get; set; }
        public string AcftTagId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
