//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontNameSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimArea
    {
        public int AreaID { get; set; }
        public string AreaName { get; set; }
        public Nullable<decimal> CenterLat { get; set; }
        public Nullable<decimal> CenterLong { get; set; }
        public System.Data.Entity.Spatial.DbGeography CenterPoint { get; set; }
        public Nullable<int> Radius { get; set; }
        public System.Data.Entity.Spatial.DbGeography Area { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocBuffer { get; set; }
        public Nullable<int> Radius_3 { get; set; }
        public Nullable<int> Radius_5 { get; set; }
        public Nullable<int> Radius_10 { get; set; }
        public Nullable<int> Radius_15 { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocBuffer_3 { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocBuffer_5 { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocBuffer_10 { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocBuffer_15 { get; set; }
    }
}
