//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontNameSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPilotLogBook
    {
        public int RouteID { get; set; }
        public string FlightDateOnly { get; set; }
        public string Comments { get; set; }
        public string AcftMMS { get; set; }
        public string Acft { get; set; }
        public Nullable<int> PilotID { get; set; }
        public Nullable<int> NoLandings { get; set; }
        public Nullable<int> FlightDurationMin { get; set; }
        public string RouteName { get; set; }
        public bool IsJunk { get; set; }
        public string AcftRegNum { get; set; }
        public Nullable<bool> IsShared { get; set; }
        public string HTMLToolTip { get; set; }
    }
}
