//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontNameSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vVisualPilotLogDestinations
    {
        public Nullable<int> PilotID { get; set; }
        public int FlightID { get; set; }
        public Nullable<decimal> flightN { get; set; }
        public decimal longitude { get; set; }
        public decimal latitude { get; set; }
        public int dest_order_id { get; set; }
        public string AirportCode { get; set; }
        public int flightweight { get; set; }
        public Nullable<int> RouteID { get; set; }
    }
}
