//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Acft_Track.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportCoordinates
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Alt { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public Nullable<decimal> LatDecimal { get; set; }
        public Nullable<decimal> LongDecimal { get; set; }
        public Nullable<int> AltDecimal { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocBuffer { get; set; }
    }
}
