//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontNameSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityGroup
    {
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupType { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string RoleName { get; set; }
    }
}
