//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontNameSpace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EntityUser
    {
        public int EntityUserID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public int GroupID { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string UserGuid { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime? Updated { get; set; }
    }
}
