//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Acft_Track.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchRequest
    {
        public int SearchID { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<int> AirportID { get; set; }
        public Nullable<int> PilotID { get; set; }
        public Nullable<int> AircraftID { get; set; }
        public string AirportCode { get; set; }
        public string AcftRegNum { get; set; }
        public string PilotCode { get; set; }
        public Nullable<int> FlightID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string AcftNumLocal { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyName { get; set; }
    }
}
