//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Acft_Track.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAircraftPilot
    {
        public int ID { get; set; }
        public int AcftID { get; set; }
        public string AcftName { get; set; }
        public string AcftTagID { get; set; }
        public string AcftMake { get; set; }
        public string AcftModel { get; set; }
        public string AcftRegNum { get; set; }
        public string AcftMMS { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string SerNum { get; set; }
        public Nullable<decimal> FlightTime { get; set; }
        public int PilotID { get; set; }
        public string PilotCode { get; set; }
        public string AcftNumLocal { get; set; }
    }
}
