//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Acft_Track.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListAircraft
    {
        public int a { get; set; }
        public string AcftID { get; set; }
        public string AcftNumLocal { get; set; }
        public Nullable<long> c { get; set; }
    }
}
