//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontNameSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vVisualPilotLogBook
    {
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> LineN { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string AcftMMS { get; set; }
        public string AcftRegNum { get; set; }
        public Nullable<int> PilotID { get; set; }
        public Nullable<int> RouteDurationMin { get; set; }
        public string RouteName { get; set; }
        public string Comments { get; set; }
        public string AirportCode { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<int> RouteNoLandings { get; set; }
        public long PK_ID { get; set; }
    }
}
